/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppVoicemailAgentRouteImport } from './routes/app.voicemail-agent'
import { Route as AppSdrAgentsRouteImport } from './routes/app.sdr-agents'
import { Route as AppSavedRouteImport } from './routes/app.saved'
import { Route as AppProductInfoRouteImport } from './routes/app.product-info'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppCoachingStylesRouteImport } from './routes/app.coaching-styles'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppOperatorIndexRouteImport } from './routes/app.operator.index'
import { Route as AppListsIndexRouteImport } from './routes/app.lists.index'
import { Route as AppOperatorThreadIdRouteImport } from './routes/app.operator.$threadId'
import { Route as AppListsListIdRouteImport } from './routes/app.lists.$listId'
import { Route as ApiOperatorChatRouteImport } from './routes/api/operator/chat'
import { Route as ApiGoogleCalendarConnectRouteImport } from './routes/api.google-calendar.connect'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api.google-calendar.callback'
import { Route as ApiRingcentralOauthCallbackRouteImport } from './routes/api/ringcentral.oauth.callback'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio.voice'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio.status'
import { Route as ApiPublicTwilioRecordingRouteImport } from './routes/api/public/twilio.recording'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicInstantlyWebhookRouteImport } from './routes/api/public/instantly.webhook'
import { Route as ApiPublicInboxIngestRouteImport } from './routes/api/public/inbox.ingest'
import { Route as ApiPublicHooksSdrReplyTickRouteImport } from './routes/api/public/hooks/sdr-reply-tick'
import { Route as ApiPublicHooksScoringTickRouteImport } from './routes/api/public/hooks/scoring-tick'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AppVoicemailAgentRoute = AppVoicemailAgentRouteImport.update({
  id: '/voicemail-agent',
  path: '/voicemail-agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrAgentsRoute = AppSdrAgentsRouteImport.update({
  id: '/sdr-agents',
  path: '/sdr-agents',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProductInfoRoute = AppProductInfoRouteImport.update({
  id: '/product-info',
  path: '/product-info',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingStylesRoute = AppCoachingStylesRouteImport.update({
  id: '/coaching-styles',
  path: '/coaching-styles',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorIndexRoute = AppOperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => AppRoute,
} as any)
const AppListsIndexRoute = AppListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorThreadIdRoute = AppOperatorThreadIdRouteImport.update({
  id: '/operator/$threadId',
  path: '/operator/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppListsListIdRoute = AppListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppRoute,
} as any)
const ApiOperatorChatRoute = ApiOperatorChatRouteImport.update({
  id: '/api/operator/chat',
  path: '/api/operator/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarConnectRoute =
  ApiGoogleCalendarConnectRouteImport.update({
    id: '/api/google-calendar/connect',
    path: '/api/google-calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRingcentralOauthCallbackRoute =
  ApiRingcentralOauthCallbackRouteImport.update({
    id: '/api/ringcentral/oauth/callback',
    path: '/api/ringcentral/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioRecordingRoute =
  ApiPublicTwilioRecordingRouteImport.update({
    id: '/api/public/twilio/recording',
    path: '/api/public/twilio/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstantlyWebhookRoute =
  ApiPublicInstantlyWebhookRouteImport.update({
    id: '/api/public/instantly/webhook',
    path: '/api/public/instantly/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInboxIngestRoute = ApiPublicInboxIngestRouteImport.update({
  id: '/api/public/inbox/ingest',
  path: '/api/public/inbox/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSdrReplyTickRoute =
  ApiPublicHooksSdrReplyTickRouteImport.update({
    id: '/api/public/hooks/sdr-reply-tick',
    path: '/api/public/hooks/sdr-reply-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScoringTickRoute =
  ApiPublicHooksScoringTickRouteImport.update({
    id: '/api/public/hooks/scoring-tick',
    path: '/api/public/hooks/scoring-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/coaching-styles': typeof AppCoachingStylesRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/people': typeof AppPeopleRoute
  '/app/product-info': typeof AppProductInfoRoute
  '/app/saved': typeof AppSavedRoute
  '/app/sdr-agents': typeof AppSdrAgentsRoute
  '/app/voicemail-agent': typeof AppVoicemailAgentRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/operator/chat': typeof ApiOperatorChatRoute
  '/app/lists/$listId': typeof AppListsListIdRoute
  '/app/operator/$threadId': typeof AppOperatorThreadIdRoute
  '/app/lists/': typeof AppListsIndexRoute
  '/app/operator/': typeof AppOperatorIndexRoute
  '/api/public/hooks/scoring-tick': typeof ApiPublicHooksScoringTickRoute
  '/api/public/hooks/sdr-reply-tick': typeof ApiPublicHooksSdrReplyTickRoute
  '/api/public/inbox/ingest': typeof ApiPublicInboxIngestRoute
  '/api/public/instantly/webhook': typeof ApiPublicInstantlyWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/ringcentral/oauth/callback': typeof ApiRingcentralOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/coaching-styles': typeof AppCoachingStylesRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/people': typeof AppPeopleRoute
  '/app/product-info': typeof AppProductInfoRoute
  '/app/saved': typeof AppSavedRoute
  '/app/sdr-agents': typeof AppSdrAgentsRoute
  '/app/voicemail-agent': typeof AppVoicemailAgentRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/operator/chat': typeof ApiOperatorChatRoute
  '/app/lists/$listId': typeof AppListsListIdRoute
  '/app/operator/$threadId': typeof AppOperatorThreadIdRoute
  '/app/lists': typeof AppListsIndexRoute
  '/app/operator': typeof AppOperatorIndexRoute
  '/api/public/hooks/scoring-tick': typeof ApiPublicHooksScoringTickRoute
  '/api/public/hooks/sdr-reply-tick': typeof ApiPublicHooksSdrReplyTickRoute
  '/api/public/inbox/ingest': typeof ApiPublicInboxIngestRoute
  '/api/public/instantly/webhook': typeof ApiPublicInstantlyWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/ringcentral/oauth/callback': typeof ApiRingcentralOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/coaching-styles': typeof AppCoachingStylesRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/people': typeof AppPeopleRoute
  '/app/product-info': typeof AppProductInfoRoute
  '/app/saved': typeof AppSavedRoute
  '/app/sdr-agents': typeof AppSdrAgentsRoute
  '/app/voicemail-agent': typeof AppVoicemailAgentRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/operator/chat': typeof ApiOperatorChatRoute
  '/app/lists/$listId': typeof AppListsListIdRoute
  '/app/operator/$threadId': typeof AppOperatorThreadIdRoute
  '/app/lists/': typeof AppListsIndexRoute
  '/app/operator/': typeof AppOperatorIndexRoute
  '/api/public/hooks/scoring-tick': typeof ApiPublicHooksScoringTickRoute
  '/api/public/hooks/sdr-reply-tick': typeof ApiPublicHooksSdrReplyTickRoute
  '/api/public/inbox/ingest': typeof ApiPublicInboxIngestRoute
  '/api/public/instantly/webhook': typeof ApiPublicInstantlyWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/ringcentral/oauth/callback': typeof ApiRingcentralOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/app/accounts'
    | '/app/admin'
    | '/app/calendar'
    | '/app/coaching-styles'
    | '/app/inbox'
    | '/app/people'
    | '/app/product-info'
    | '/app/saved'
    | '/app/sdr-agents'
    | '/app/voicemail-agent'
    | '/checkout/return'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/operator/chat'
    | '/app/lists/$listId'
    | '/app/operator/$threadId'
    | '/app/lists/'
    | '/app/operator/'
    | '/api/public/hooks/scoring-tick'
    | '/api/public/hooks/sdr-reply-tick'
    | '/api/public/inbox/ingest'
    | '/api/public/instantly/webhook'
    | '/api/public/payments/webhook'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
    | '/api/ringcentral/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/app/accounts'
    | '/app/admin'
    | '/app/calendar'
    | '/app/coaching-styles'
    | '/app/inbox'
    | '/app/people'
    | '/app/product-info'
    | '/app/saved'
    | '/app/sdr-agents'
    | '/app/voicemail-agent'
    | '/checkout/return'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/operator/chat'
    | '/app/lists/$listId'
    | '/app/operator/$threadId'
    | '/app/lists'
    | '/app/operator'
    | '/api/public/hooks/scoring-tick'
    | '/api/public/hooks/sdr-reply-tick'
    | '/api/public/inbox/ingest'
    | '/api/public/instantly/webhook'
    | '/api/public/payments/webhook'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
    | '/api/ringcentral/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/login'
    | '/pricing'
    | '/app/accounts'
    | '/app/admin'
    | '/app/calendar'
    | '/app/coaching-styles'
    | '/app/inbox'
    | '/app/people'
    | '/app/product-info'
    | '/app/saved'
    | '/app/sdr-agents'
    | '/app/voicemail-agent'
    | '/checkout/return'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/operator/chat'
    | '/app/lists/$listId'
    | '/app/operator/$threadId'
    | '/app/lists/'
    | '/app/operator/'
    | '/api/public/hooks/scoring-tick'
    | '/api/public/hooks/sdr-reply-tick'
    | '/api/public/inbox/ingest'
    | '/api/public/instantly/webhook'
    | '/api/public/payments/webhook'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
    | '/api/ringcentral/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarConnectRoute: typeof ApiGoogleCalendarConnectRoute
  ApiOperatorChatRoute: typeof ApiOperatorChatRoute
  ApiPublicHooksScoringTickRoute: typeof ApiPublicHooksScoringTickRoute
  ApiPublicHooksSdrReplyTickRoute: typeof ApiPublicHooksSdrReplyTickRoute
  ApiPublicInboxIngestRoute: typeof ApiPublicInboxIngestRoute
  ApiPublicInstantlyWebhookRoute: typeof ApiPublicInstantlyWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTwilioRecordingRoute: typeof ApiPublicTwilioRecordingRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
  ApiRingcentralOauthCallbackRoute: typeof ApiRingcentralOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/app/voicemail-agent': {
      id: '/app/voicemail-agent'
      path: '/voicemail-agent'
      fullPath: '/app/voicemail-agent'
      preLoaderRoute: typeof AppVoicemailAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr-agents': {
      id: '/app/sdr-agents'
      path: '/sdr-agents'
      fullPath: '/app/sdr-agents'
      preLoaderRoute: typeof AppSdrAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product-info': {
      id: '/app/product-info'
      path: '/product-info'
      fullPath: '/app/product-info'
      preLoaderRoute: typeof AppProductInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching-styles': {
      id: '/app/coaching-styles'
      path: '/coaching-styles'
      fullPath: '/app/coaching-styles'
      preLoaderRoute: typeof AppCoachingStylesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/': {
      id: '/app/operator/'
      path: '/operator'
      fullPath: '/app/operator/'
      preLoaderRoute: typeof AppOperatorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lists/': {
      id: '/app/lists/'
      path: '/lists'
      fullPath: '/app/lists/'
      preLoaderRoute: typeof AppListsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator/$threadId': {
      id: '/app/operator/$threadId'
      path: '/operator/$threadId'
      fullPath: '/app/operator/$threadId'
      preLoaderRoute: typeof AppOperatorThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lists/$listId': {
      id: '/app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/app/lists/$listId'
      preLoaderRoute: typeof AppListsListIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/operator/chat': {
      id: '/api/operator/chat'
      path: '/api/operator/chat'
      fullPath: '/api/operator/chat'
      preLoaderRoute: typeof ApiOperatorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/connect': {
      id: '/api/google-calendar/connect'
      path: '/api/google-calendar/connect'
      fullPath: '/api/google-calendar/connect'
      preLoaderRoute: typeof ApiGoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ringcentral/oauth/callback': {
      id: '/api/ringcentral/oauth/callback'
      path: '/api/ringcentral/oauth/callback'
      fullPath: '/api/ringcentral/oauth/callback'
      preLoaderRoute: typeof ApiRingcentralOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/recording': {
      id: '/api/public/twilio/recording'
      path: '/api/public/twilio/recording'
      fullPath: '/api/public/twilio/recording'
      preLoaderRoute: typeof ApiPublicTwilioRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instantly/webhook': {
      id: '/api/public/instantly/webhook'
      path: '/api/public/instantly/webhook'
      fullPath: '/api/public/instantly/webhook'
      preLoaderRoute: typeof ApiPublicInstantlyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbox/ingest': {
      id: '/api/public/inbox/ingest'
      path: '/api/public/inbox/ingest'
      fullPath: '/api/public/inbox/ingest'
      preLoaderRoute: typeof ApiPublicInboxIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sdr-reply-tick': {
      id: '/api/public/hooks/sdr-reply-tick'
      path: '/api/public/hooks/sdr-reply-tick'
      fullPath: '/api/public/hooks/sdr-reply-tick'
      preLoaderRoute: typeof ApiPublicHooksSdrReplyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scoring-tick': {
      id: '/api/public/hooks/scoring-tick'
      path: '/api/public/hooks/scoring-tick'
      fullPath: '/api/public/hooks/scoring-tick'
      preLoaderRoute: typeof ApiPublicHooksScoringTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCoachingStylesRoute: typeof AppCoachingStylesRoute
  AppInboxRoute: typeof AppInboxRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppProductInfoRoute: typeof AppProductInfoRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSdrAgentsRoute: typeof AppSdrAgentsRoute
  AppVoicemailAgentRoute: typeof AppVoicemailAgentRoute
  AppListsListIdRoute: typeof AppListsListIdRoute
  AppOperatorThreadIdRoute: typeof AppOperatorThreadIdRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
  AppOperatorIndexRoute: typeof AppOperatorIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAdminRoute: AppAdminRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCoachingStylesRoute: AppCoachingStylesRoute,
  AppInboxRoute: AppInboxRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppProductInfoRoute: AppProductInfoRoute,
  AppSavedRoute: AppSavedRoute,
  AppSdrAgentsRoute: AppSdrAgentsRoute,
  AppVoicemailAgentRoute: AppVoicemailAgentRoute,
  AppListsListIdRoute: AppListsListIdRoute,
  AppOperatorThreadIdRoute: AppOperatorThreadIdRoute,
  AppListsIndexRoute: AppListsIndexRoute,
  AppOperatorIndexRoute: AppOperatorIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarConnectRoute: ApiGoogleCalendarConnectRoute,
  ApiOperatorChatRoute: ApiOperatorChatRoute,
  ApiPublicHooksScoringTickRoute: ApiPublicHooksScoringTickRoute,
  ApiPublicHooksSdrReplyTickRoute: ApiPublicHooksSdrReplyTickRoute,
  ApiPublicInboxIngestRoute: ApiPublicInboxIngestRoute,
  ApiPublicInstantlyWebhookRoute: ApiPublicInstantlyWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTwilioRecordingRoute: ApiPublicTwilioRecordingRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
  ApiRingcentralOauthCallbackRoute: ApiRingcentralOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
